-- MOTORCART.IN — Schema reference (apply migrations in order)
-- 00001_complete_backend.sql   — Core 20 tables, RLS, storage, auth trigger
-- 00002_vehicle_marketplace.sql — Public lead capture
-- 00003_auctions_realtime.sql  — Live bids RPC, auction chat
-- 00004_finance_marketplace.sql — Lenders, DSA, finance docs
-- 00005_parts_marketplace.sql  — Part orders, checkout RPC
-- 00006_automotive_services.sql — Service hub, OTP, technician
-- 00007_community_social.sql   — Social feed, moderation
-- 00008_backend_completion.sql — vehicle_images, vehicle_specs, CRM, RLS fixes, realtime
