import type { LucideIcon } from "lucide-react";
import {
  AlertTriangle,
  BarChart3,
  Bell,
  Bot,
  Boxes,
  Building2,
  ClipboardList,
  FileSpreadsheet,
  GitBranch,
  Landmark,
  LayoutDashboard,
  Layers,
  Megaphone,
  MessageSquare,
  Package,
  PackagePlus,
  Percent,
  QrCode,
  Settings,
  Shield,
  ShoppingCart,
  Truck,
  Upload,
  UserCog,
  Users,
  Warehouse,
  Wrench,
  Zap,
  Mail,
  Tags,
} from "lucide-react";

export type PsNavItem = { to: string; label: string; icon: LucideIcon; end?: boolean };
export type PsNavGroup = { label: string; items: PsNavItem[] };

export const PARTS_SUPPLIER_NAV: PsNavGroup[] = [
  {
    label: "Overview",
    items: [
      { to: "/dashboard/parts", label: "Dashboard", icon: LayoutDashboard, end: true },
      { to: "/dashboard/parts/ai", label: "AI insights", icon: Bot },
      { to: "/dashboard/parts/orders", label: "Live orders", icon: Zap },
      { to: "/dashboard/parts/alerts", label: "Smart alerts", icon: Bell },
    ],
  },
  {
    label: "Catalog",
    items: [
      { to: "/dashboard/parts/catalog", label: "All products", icon: Package },
      { to: "/dashboard/parts/upload", label: "Add product", icon: PackagePlus },
      { to: "/dashboard/parts/bulk-upload", label: "Bulk upload", icon: Upload },
      { to: "/dashboard/parts/categories", label: "Categories", icon: Boxes },
      { to: "/dashboard/parts/brands", label: "Brands", icon: Building2 },
      { to: "/dashboard/parts/variants", label: "Variants", icon: Layers },
      { to: "/dashboard/parts/oem-mapping", label: "OEM mapping", icon: Tags },
      { to: "/dashboard/parts/compatibility", label: "Compatibility", icon: Wrench },
    ],
  },
  {
    label: "Inventory",
    items: [
      { to: "/dashboard/parts/inventory", label: "Stock & SKUs", icon: Warehouse },
      { to: "/dashboard/parts/warehouses", label: "Warehouses", icon: Building2 },
      { to: "/dashboard/parts/racks", label: "Rack management", icon: GitBranch },
      { to: "/dashboard/parts/low-stock", label: "Low stock", icon: AlertTriangle },
      { to: "/dashboard/parts/dead-stock", label: "Dead stock", icon: Package },
      { to: "/dashboard/parts/incoming", label: "Incoming inventory", icon: Truck },
      { to: "/dashboard/parts/transfers", label: "Inventory transfers", icon: ClipboardList },
    ],
  },
  {
    label: "Orders",
    items: [
      { to: "/dashboard/parts/orders/new", label: "New orders", icon: ShoppingCart },
      { to: "/dashboard/parts/orders/processing", label: "Processing", icon: ClipboardList },
      { to: "/dashboard/parts/orders/packed", label: "Packed", icon: Package },
      { to: "/dashboard/parts/orders/dispatched", label: "Dispatched", icon: Truck },
      { to: "/dashboard/parts/orders/delivered", label: "Delivered", icon: Truck },
      { to: "/dashboard/parts/orders/returns", label: "Returned", icon: Package },
      { to: "/dashboard/parts/orders/cancelled", label: "Cancelled", icon: Package },
    ],
  },
  {
    label: "B2B CRM",
    items: [
      { to: "/dashboard/parts/crm/dealers", label: "Dealers", icon: Building2 },
      { to: "/dashboard/parts/crm/garages", label: "Garages", icon: Wrench },
      { to: "/dashboard/parts/crm/workshops", label: "Workshops", icon: Users },
      { to: "/dashboard/parts/crm/repeat", label: "Repeat buyers", icon: ShoppingCart },
      { to: "/dashboard/parts/crm/negotiations", label: "Negotiations", icon: MessageSquare },
      { to: "/dashboard/parts/crm/pipeline", label: "Lead pipeline", icon: GitBranch },
      { to: "/dashboard/parts/crm/rfq", label: "Bulk RFQ", icon: FileSpreadsheet },
    ],
  },
  {
    label: "Pricing",
    items: [
      { to: "/dashboard/parts/pricing/retail", label: "Retail pricing", icon: Percent },
      { to: "/dashboard/parts/pricing/dealer", label: "Dealer pricing", icon: Percent },
      { to: "/dashboard/parts/pricing/wholesale", label: "Wholesale pricing", icon: Percent },
      { to: "/dashboard/parts/pricing/bulk", label: "Bulk pricing", icon: Percent },
      { to: "/dashboard/parts/pricing/dynamic", label: "Dynamic pricing", icon: Zap },
      { to: "/dashboard/parts/pricing/offers", label: "Offers & coupons", icon: Megaphone },
    ],
  },
  {
    label: "Logistics",
    items: [
      { to: "/dashboard/parts/logistics/dispatch", label: "Dispatch center", icon: Zap },
      { to: "/dashboard/parts/logistics/couriers", label: "Courier partners", icon: Truck },
      { to: "/dashboard/parts/logistics/tracking", label: "Shipment tracking", icon: ClipboardList },
      { to: "/dashboard/parts/logistics/sla", label: "Delivery SLA", icon: AlertTriangle },
      { to: "/dashboard/parts/logistics/labels", label: "Shipping labels", icon: FileSpreadsheet },
    ],
  },
  {
    label: "Procurement",
    items: [
      { to: "/dashboard/parts/procurement/po", label: "Purchase orders", icon: FileSpreadsheet },
      { to: "/dashboard/parts/procurement/vendors", label: "Vendors", icon: Building2 },
      { to: "/dashboard/parts/procurement/bills", label: "Supplier bills", icon: Landmark },
      { to: "/dashboard/parts/procurement/incoming", label: "Incoming stock", icon: Truck },
    ],
  },
  {
    label: "Finance",
    items: [
      { to: "/dashboard/parts/finance/revenue", label: "Revenue", icon: Landmark },
      { to: "/dashboard/parts/finance/invoices", label: "GST invoices", icon: FileSpreadsheet },
      { to: "/dashboard/parts/finance/payouts", label: "Payouts", icon: Landmark },
      { to: "/dashboard/parts/finance/settlements", label: "Settlements", icon: Landmark },
      { to: "/dashboard/parts/finance/credit-notes", label: "Credit notes", icon: FileSpreadsheet },
      { to: "/dashboard/parts/finance/profit", label: "Profit reports", icon: BarChart3 },
    ],
  },
  {
    label: "Marketing",
    items: [
      { to: "/dashboard/parts/marketing/whatsapp", label: "WhatsApp campaigns", icon: MessageSquare },
      { to: "/dashboard/parts/marketing/sms", label: "SMS campaigns", icon: MessageSquare },
      { to: "/dashboard/parts/marketing/email", label: "Email campaigns", icon: Mail },
      { to: "/dashboard/parts/marketing/catalogue", label: "Catalogue sharing", icon: Package },
    ],
  },
  {
    label: "Analytics",
    items: [
      { to: "/dashboard/parts/analytics/revenue", label: "Revenue analytics", icon: BarChart3 },
      { to: "/dashboard/parts/analytics/products", label: "Product analytics", icon: Package },
      { to: "/dashboard/parts/analytics/warehouse", label: "Warehouse analytics", icon: Warehouse },
      { to: "/dashboard/parts/analytics/customers", label: "Customer analytics", icon: Users },
      { to: "/dashboard/parts/analytics/sku", label: "SKU performance", icon: Zap },
    ],
  },
  {
    label: "Settings",
    items: [
      { to: "/dashboard/parts/profile", label: "Business profile", icon: Settings },
      { to: "/dashboard/parts/kyc", label: "KYC & verification", icon: Shield },
      { to: "/dashboard/parts/staff", label: "Staff & roles", icon: UserCog },
      { to: "/dashboard/parts/notifications", label: "Notifications", icon: Bell },
      { to: "/dashboard/parts/automation", label: "Automation", icon: Bot },
      { to: "/dashboard/parts/barcode", label: "Barcode & QR", icon: QrCode },
      { to: "/dashboard/parts/storefront", label: "Public storefront", icon: Package },
      { to: "/dashboard/parts/whatsapp", label: "WhatsApp commerce", icon: MessageSquare },
    ],
  },
];
