/** Canonical Excel/CSV column headers for bulk inventory upload */
export const INVENTORY_COLUMNS = [
  "Brand",
  "Model",
  "Variant",
  "Year",
  "Fuel",
  "Transmission",
  "KM Driven",
  "Ownership",
  "Price",
  "Color",
  "Registration State",
  "Description",
  "Dealer Price",
  "Discount",
  "Main Image URL",
] as const;

export type InventoryColumn = (typeof INVENTORY_COLUMNS)[number];

/** Header aliases (case-insensitive) → canonical column */
export const COLUMN_ALIASES: Record<string, InventoryColumn> = {
  brand: "Brand",
  model: "Model",
  variant: "Variant",
  year: "Year",
  fuel: "Fuel",
  "fuel type": "Fuel",
  transmission: "Transmission",
  "km driven": "KM Driven",
  kms: "KM Driven",
  kilometers: "KM Driven",
  ownership: "Ownership",
  owners: "Ownership",
  price: "Price",
  "selling price": "Price",
  color: "Color",
  "registration state": "Registration State",
  state: "Registration State",
  description: "Description",
  "dealer price": "Dealer Price",
  discount: "Discount",
  "main image url": "Main Image URL",
  image: "Main Image URL",
  "image url": "Main Image URL",
};

export const SAMPLE_ROW: Record<InventoryColumn, string | number> = {
  Brand: "Hyundai",
  Model: "Creta",
  Variant: "SX(O)",
  Year: 2023,
  Fuel: "Diesel",
  Transmission: "Automatic",
  "KM Driven": 18500,
  Ownership: 1,
  Price: 1485000,
  Color: "White",
  "Registration State": "Maharashtra",
  Description: "Single owner, full service history",
  "Dealer Price": 1450000,
  Discount: 3,
  "Main Image URL": "https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800",
};
