export { CUSTOMER_ECOSYSTEM_NAV } from "./config/customer-nav";
export { useCustomerEcosystem } from "./hooks/useCustomerEcosystem";
export type { CustomerEcosystemSnapshot } from "./types";
export { CustomerGaragePage } from "./pages/CustomerGaragePage";
export { CustomerAddVehiclePage } from "./pages/CustomerAddVehiclePage";
export { CustomerDocumentsPage } from "./pages/CustomerDocumentsPage";
export { CustomerInsuranceWalletPage } from "./pages/CustomerInsuranceWalletPage";
export { CustomerInsightsPage } from "./pages/CustomerInsightsPage";
export { CustomerNotificationsPage } from "./pages/CustomerNotificationsPage";
export { CustomerRewardsPage } from "./pages/CustomerRewardsPage";
export { CustomerProfileCenterPage } from "./pages/CustomerProfileCenterPage";
export { CustomerFastagPage } from "./pages/CustomerFastagPage";
export { CustomerServiceRecordsPage } from "./pages/CustomerServiceRecordsPage";
export { CustomerVehicleHealthPage } from "./pages/CustomerVehicleHealthPage";
export { CustomerRecentlyViewedPage } from "./pages/CustomerRecentlyViewedPage";
export { previewAutomationForUser } from "./services/customer-automation.service";
